---
kind: pipeline
name: default

steps:
- name: staging
  image: hackercowboy/dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: appl
    path: /appl
  commands:
  - docker build -t codecowboys:staging .
  - cd /appl;docker-compose up -d
  when:
    branch:
    - development
    event:
    - push
- name: production
  image: hackercowboy/dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  - name: appl
    path: /appl
  commands:
  - docker build -t codecowboys:production .
  - cd /appl;docker-compose up -d
  when:
    branch:
    - master
    event:
    - push
volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: appl
  host:
    path: /appl
